# Generated by Django 4.2.11 on 2025-10-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
